// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79CTRfspU1k6qq6IpNCA8emIaRF3dZqE',
    appId: '1:601345680928:web:2b07db0f8e87767ca47e45',
    messagingSenderId: '601345680928',
    projectId: 'first-flutter-b5dad',
    authDomain: 'first-flutter-b5dad.firebaseapp.com',
    storageBucket: 'first-flutter-b5dad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCToukyaAPISvGz6fL1zAfXaTkZi17skxs',
    appId: '1:601345680928:android:36304b570f78f8dca47e45',
    messagingSenderId: '601345680928',
    projectId: 'first-flutter-b5dad',
    storageBucket: 'first-flutter-b5dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSuc2iMgxCvqPXw1NP01TU4x-lpbeLgss',
    appId: '1:601345680928:ios:dc19e1badcc5ae8da47e45',
    messagingSenderId: '601345680928',
    projectId: 'first-flutter-b5dad',
    storageBucket: 'first-flutter-b5dad.appspot.com',
    iosClientId: '601345680928-97hndoi2h7jj85h0i9udg0erchkq9d3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.halfwaynew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSuc2iMgxCvqPXw1NP01TU4x-lpbeLgss',
    appId: '1:601345680928:ios:2e7b69bd7004986aa47e45',
    messagingSenderId: '601345680928',
    projectId: 'first-flutter-b5dad',
    storageBucket: 'first-flutter-b5dad.appspot.com',
    iosClientId: '601345680928-b7u1med2o8m3vvphpgo55bmdl56io8e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.halfwaynew.RunnerTests',
  );
}
