// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCK7uHfKY9_LYQfMsGNi-zEcqYeZ8ukj0',
    appId: '1:500565607506:web:5f602c81c9eed1cde04b8b',
    messagingSenderId: '500565607506',
    projectId: 'halfwaymappls01',
    authDomain: 'halfwaymappls01.firebaseapp.com',
    storageBucket: 'halfwaymappls01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcnfB4SZ8mP5SudVCpUE9LXs_GaDSUcc',
    appId: '1:500565607506:android:5eaf386db1765db5e04b8b',
    messagingSenderId: '500565607506',
    projectId: 'halfwaymappls01',
    storageBucket: 'halfwaymappls01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVMyc0FXlcI87uREe0f1tLkKS7CgRza3c',
    appId: '1:500565607506:ios:568bf51b28e8a226e04b8b',
    messagingSenderId: '500565607506',
    projectId: 'halfwaymappls01',
    storageBucket: 'halfwaymappls01.appspot.com',
    iosBundleId: 'com.example.halfwaymappls01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVMyc0FXlcI87uREe0f1tLkKS7CgRza3c',
    appId: '1:500565607506:ios:a76822f2d9ede89ae04b8b',
    messagingSenderId: '500565607506',
    projectId: 'halfwaymappls01',
    storageBucket: 'halfwaymappls01.appspot.com',
    iosBundleId: 'com.example.halfwaymappls01.RunnerTests',
  );
}
